<a href="https://colab.research.google.com/github/jayakrishnavamsi24/Colab-repositories/blob/main/Copy_of_Numpy_Practice_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Welcome to the NumPy practice exercise! Please follow these instructions carefully to complete your assignment:

1. **Read Each Question Carefully**: Each question is designed to test different aspects of your NumPy skills. Make sure to understand what is being asked before you start coding.

2. **Write Your Code in the Provided Cells**: For each question, you will find a corresponding code cell where you should write your solution. Do not modify any other part of the notebook.

3. **Run Your Code**: After writing your code, run the cell to ensure that your solution works as expected. Check the output and make sure it meets the requirements specified in the question.

4. **Complete All Questions**: Make sure you answer all the questions provided. Each question has been included to assess a different skill or concept in NumPy.

5. **Download Your Notebook**: Once you have completed all questions and verified that your solutions are correct, download your notebook file (.ipynb). You can do this by selecting `File > Download > Download .ipynb` from the menu.

6. **Submit Your Work**: Upload the downloaded `.ipynb` file to the designated learning platform for submission.

7. **Check Your Submission**: Ensure that you have submitted the correct file and that it is not corrupted. If there are any issues with the file, you may need to resubmit.

Good luck, and happy coding!

Q1. Import Numpy as `np`

In [1]:
# write your code here
import numpy as np

Q.2 Create a 5x5 array, with numbers ranging from 1-25 and save it in `matrix` variable.
(Use `matrix` variable till question no 10.)

In [7]:
# write your code here
matrix = np.arange(1, 26).reshape((5, 5))
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Q.3 select the subset from `matrix`
```python
array([12,13,14,15],
      [17,18,18,20],
      [22,23,24,25])
```

In [8]:
# write your code here
matrix[2:5, 1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

Q.4 Select the value 20 from the `matrix`

In [9]:
# write your code here
matrix[3][4]

20

Q.5 Select the below subset.(Use `matrix`)
```python
array([[2],
      [7],
      [12]])
```


In [11]:
# write your code here
matrix[0:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

Q.6 Select the below subset. (Use `matrix`)
```python
array([21,22,23,24,25])
```

In [13]:
# write your code here
matrix[4]

array([21, 22, 23, 24, 25])

Q.7 Select the subset below (Use `matrix`)
```python
array([[16,17,18,19,20],
       [21,22,23,24,25]])
```



In [14]:
# write your code here
matrix[-2:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Q.8 Get the sum of all the values in `matrix`. (Expected Ans : 325)

In [15]:
# write your code here
np.sum(matrix)

325

Q.9 Get the standard deviation of the values in `matrix`(Expected Ans : 7.2111025)

In [16]:
# write your code here
matrix.std()

7.211102550927978

Q. 10 Get the sum of all the columns in `matrix`. (Expected Ans: array([55,60,65,70,75])

In [19]:
# write your code here
np.sum(matrix, axis=0)

array([55, 60, 65, 70, 75])

Q.11 Reverse a 1D array.

In [22]:
# write your code here
a1 = np.arange(1, 11)
a1 = a1[::-1]
a1

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

Q.12 Find indices of non-zero elements from [10,20,0,0,40,0]





In [31]:
# write your code here
a2 = [10, 20, 0, 0, 40, 0]
a2 = np.nonzero(a2)
a2

(array([0, 1, 4]),)

Q.13 Create a 10x10 array with random values and find the minimum and maximum values.

In [46]:
# write your code here
rdv_arr = np.random.randint(1, 101, (10, 10))
min_val = np.min(rdv_arr)
max_val = np.max(rdv_arr)
print("Random 10x10 array", rdv_arr)
print("Minimum Value", min_val)
print("Maximum Value", max_val)

Random 10x10 array [[75 65 92 97 98 43  8 50 63 24]
 [46 88 79 71 58  6 12  8 38 29]
 [33 44 30 61 75 60 13 92 46 51]
 [87 90 88 84 35 81 37 36 51 60]
 [67 65 46 47 37 95 24 47 99 65]
 [17 15 19 62 44 60 68 75  3 71]
 [89 85  8 35 88 63 22 24 43 26]
 [75 55 50 49 83 22 19 30 95 69]
 [66 82 45 84 36 89 31 76 44 46]
 [42 42 68 47 29 56 24 96 74 43]]
Minimum Value 3
Maximum Value 99


Q.14 Create a 10x10 array with 1 on the border and 0 inside.

In [48]:
# write your code here
ones_arr = np.ones((10, 10), dtype=int)
ones_arr[1:-1, 1:-1] = 0
ones_arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

Q. 15 Create 8x8 array and fill it with the cheakerboard pattern.


In [52]:
# write your code here
ones_arr = np.ones((8, 8), dtype=int)
ones_arr[0:9:2, 1:9:2] = 0
ones_arr[1:9:2, 0:9:2] = 0
ones_arr

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

Q.16 Create a numpy array of size 10 with values ranging from 0 to 1, both excluded.

In [54]:
# write your code here
np.linspace(0, 1, 12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

Q.17 Create a random array of size 10 and sort it.

In [62]:
# write your code here
a1 = np.random.rand(10)
a1.sort()
a1

array([0.06298494, 0.21517653, 0.38799357, 0.56687193, 0.72833533,
       0.75043389, 0.81511079, 0.81786795, 0.86228772, 0.97820586])

Q.18 Create a random array of size 10 and replace the maximum value with 0.

In [65]:
# write your code here
a2 = np.random.rand(10)
a2[np.argmax(a2)] = 0
a2

array([0.37738054, 0.06294128, 0.29536423, 0.74485052, 0.        ,
       0.79983245, 0.76854833, 0.13724993, 0.64434603, 0.11687345])

Q.19 Create a random array of size 10 and replace the minimum value with 10.

In [66]:
# write your code here
a3 = np.random.rand(10)
a3[np.argmin(a3)] = 10
a3

array([ 0.79918409,  0.74898635,  0.30671918,  0.1288117 ,  0.69231423,
        0.31784732,  0.40326437,  0.62616618,  0.24352836, 10.        ])

Q.20 Create an array of size 5x5 and swap two rows.

In [71]:
 # write your code here
 a4 = np.arange(1, 26).reshape((5, 5))
 temp = np.copy(a4[1])
 a4[1] = a4[0]
 a4[0] = temp
 a4

array([[ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

# End!