Welcome to the NumPy practice exercise! Please follow these instructions carefully to complete your assignment:

1. **Read Each Question Carefully**: Each question is designed to test different aspects of your NumPy skills. Make sure to understand what is being asked before you start coding.

2. **Write Your Code in the Provided Cells**: For each question, you will find a corresponding code cell where you should write your solution. Do not modify any other part of the notebook.

3. **Run Your Code**: After writing your code, run the cell to ensure that your solution works as expected. Check the output and make sure it meets the requirements specified in the question.

4. **Complete All Questions**: Make sure you answer all the questions provided. Each question has been included to assess a different skill or concept in NumPy.

5. **Download Your Notebook**: Once you have completed all questions and verified that your solutions are correct, download your notebook file (.ipynb). You can do this by selecting `File > Download > Download .ipynb` from the menu.

6. **Submit Your Work**: Upload the downloaded `.ipynb` file to the designated learning platform for submission.

7. **Check Your Submission**: Ensure that you have submitted the correct file and that it is not corrupted. If there are any issues with the file, you may need to resubmit.

Good luck, and happy coding!

Q1. Import Numpy as `np`

In [1]:
# write your code here
import numpy as np


Q2. Create an array of 10 zeros.

In [2]:
# write your code here
a1 = np.zeros(10)
a1


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Q3. Create an array of 10 ones and the fifth value which is 0.

In [3]:
# write your code here
a2 = np.ones(10)
a2[4] = 0
a2


array([1., 1., 1., 1., 0., 1., 1., 1., 1., 1.])

Q.4 Create an array of 10 fives

In [4]:
# write your code here
a3 = np.full(10, fill_value=5)
a3

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

Q.5 Create an array of the integers from 10 to 50.

In [5]:
# write your code here
a4 = np.arange(10, 51)
a4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

Q.6 Create an array of all even integers from 10 to 50.

In [6]:
# write your code here
a5 = np.arange(10, 51, 2)
a5

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

Q.7 Create a 3x3 matrix with values ranging from 0 to 8.




In [9]:
# write your code here
a6 = np.arange(0, 9)
a6 = a6.reshape((3,3))
a6

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Q.8 Create a 3x3 identity matrix.

In [12]:
# write your code here
a7 = np.eye(3)
a7

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Q.9 Use numpy to generate a random number between 0 to 1.

In [18]:
# write your code here
a8 = np.random.rand(1)
a8

array([0.38972162])

Q.10 Use numpy array to generate an array of 25 numbers.

In [19]:
# write your code here
a9 = np.random.rand(25)
a9

array([0.52157531, 0.81444928, 0.67824878, 0.7364375 , 0.09454771,
       0.98336712, 0.10826184, 0.71396487, 0.20866692, 0.36151196,
       0.00198325, 0.76190143, 0.85155761, 0.24654285, 0.52855524,
       0.40463414, 0.18210357, 0.02053195, 0.11193876, 0.267083  ,
       0.01047554, 0.59245344, 0.24004421, 0.93238983, 0.00711171])

Q.11 create the following matrix

```python
array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

  ```

In [21]:
# write your code here
a10 = np.arange(0.01, 1.01, 0.01)
a10

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

Q.12 Create an array of 20 linearly spaced points between 0 and 1.

1.   List item
2.   List item



In [22]:
# write your code here
a11 = np.linspace(0, 1, 20)
a11

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

# End!